[smith]
timeout = 8
namespace = "smith"

[agent]
monitor = false
singleton = true
metadata = ""
prefetch = 1

# Specify the VM that an agent should use.
[vm]
agent_default = "ruby"

[eventmachine]
epoll = true
kqueue = true

[agency]
# The the agency pid path. This can be overriden on the command line.
pid_directory = "~/.smith/run"
cache_directory = "~/.smith/cache"

# This is the directory that will contain the agent groups
group_directory = "groups"

# It would be better to use inline tables here but there is a bug in
# toml-rb: https://github.com/emancu/toml-rb/issues/57.
# TODO: Change these to inline tables when this bug is fixed.
[amqp.exchange]
durable = true
auto_delete = false

[amqp.queue]
durable = true
auto_delete = false

[amqp.pop]
ack = true

[amqp.publish.headers]
# headers = {}},

[amqp.subscribe]
ack = true

# Change according to your local broker.
[amqp.broker]
# host = "localhost"
# port = 5672
# user = "guest"
# password = "guest"
# vhost = "/smith"

uri = "amqp://guest:guest@basking:5672"

[logging]
trace = true
level = "debug"

# Log pattern. Note you need to escape backslashes.
default_pattern = "%d [%5p] %7l - %34c:%-3L - %m\n"
default_date_pattern = "%Y/%m/%d %H:%M:%S.%3N"

# This can be either: stderr, stdout, file, rollingfile or syslog
[logging.appender]
type      = "stderr"
